# Generated by Django 2.0.2 on 2018-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('real_name', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('last_login', models.DateTimeField(verbose_name='last login')),
            ],
        ),
    ]
