# Generated by Django 2.0.2 on 2018-02-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='real_name',
            new_name='realname',
        ),
    ]
