# Generated by Django 2.0.2 on 2018-02-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0006_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=200)),
                ('token_id', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('totp_step', models.CharField(max_length=200)),
                ('user', models.ManyToManyField(to='duo.User')),
            ],
        ),
    ]
