# Generated by Django 2.0.2 on 2018-02-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0007_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='serial',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='totp_step',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
