# Generated by Django 2.0.2 on 2018-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0009_auto_20180214_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='duo.User'),
        ),
    ]
