# Generated by Django 2.0.2 on 2018-03-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0010_group_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=200, null=True)),
                ('extension', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('platform', models.CharField(max_length=200, null=True)),
                ('postdelay', models.CharField(max_length=200, null=True)),
                ('predelay', models.CharField(max_length=200, null=True)),
                ('sms_passcodes_sent', models.CharField(max_length=200, null=True)),
                ('actived', models.CharField(max_length=200, null=True)),
                ('users', models.ManyToManyField(to='duo.User')),
            ],
        ),
    ]
