# Generated by Django 2.0.2 on 2018-03-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0011_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='actived',
            new_name='activated',
        ),
    ]
